---
env:
  node: true
  browser: true
parser: babel-eslint
extends:
  - airbnb
rules:
  arrow-body-style: [2, "as-needed"]
  no-param-reassign: ["error", {"props":false}]
  import/prefer-default-export: 1

