language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

script: npm run test:infrastructure

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    #   script: npm run test:services