language: node_js

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      node_js:
        - "8"
        - "lts/*"
        - "node"

      cache:
        directories:
          - "node_modules"
      script: npm run test:infrastructure


    #   script: npm run test:services